import React from 'react';

export default function Terms() {
  return (
    <div className="max-w-6xl mx-auto container">
      <section className=" backdrop-filter backdrop-blur-sm bg-opacity-50 rounded-xl m-5">
        <div className="flex flex-col items-center justify-center py-3">
          <span className="text-4xl font-bold text-gray-800">
            Terms and Conditions
          </span>
          <span className="px-5  py-8 text-md md:text-xl text-gray-800 max-w-5xl ">
            Welcome to{' '}
            <a
              href="https://www.bluepen.co.in/"
              className="text-blue-500 hover:text-blue-700 px-2"
            >
              www.bluepen.co.in!
            </a>
            Bluepen Assignment Private Limited provides you with original, freshly made assignments at
            very low prices. If you wish to become a member of our venture and
            delegate your academic responsibilities to us, you must first agree
            to and accept our terms of service. Ordering a document indicates
            your approval, thus it is best to read all of the relevant
            information on our pages before placing an order. This is to ensure
            that our transactions are completely transparent and to avoid any
            future misunderstandings. This document is an electronic record in
            terms of Information Technology Act, 2000 and rules there under as
            applicable and the amended provisions pertaining to electronic
            records in various statutes as amended by the Information Technology
            Act, 2000. This electronic record is generated by a computer system
            and does not require any physical or digital signatures. This
            document is published in accordance with the provisions of Rule 3
            (1) of the Information Technology (Intermediaries guidelines) Rules,
            2011 that require publishing the rules and regulations, privacy
            policy and Terms of Use for access or usage of www.bluepen.co.in
            website. The following terminology applies to these Terms and
            Conditions, Privacy Statement and Disclaimer Notice and all
            Agreements: "Client", "You" and "Your" refers to you, the person log
            on this website and compliant to the Company’s terms and conditions.
            "The Company", "Ourselves", "We", "Our" and "Us", refers to our
            Company. "Party", "Parties", or "Us", refers to both the Client and
            ourselves. All terms refer to the offer, acceptance and
            consideration of payment necessary to undertake the process of our
            assistance to the Client in the most appropriate manner for the
            express purpose of meeting the Client’s needs in respect of
            provision of the Company’s stated services, in accordance with and
            subject to, prevailing law of Netherlands. Any use of the above
            terminology or other words in the singular, plural, capitalization
            and/or he/she or they, are taken as interchangeable and therefore as
            referring to the same.
          </span>
          <span className="text-xl text-left font-bold">Disclaimer(Terms)</span>
          <span className="px-5  py-8 text-md md:text-xl text-gray-800 max-w-5xl ">
            <ul className="list-disc list-inside">
              <li>
              Bluepen does not promote or indulge in any kind of activities
                pertaining to assistance in examinations.
              </li>
              <li>
              Bluepen is not responsible for the marks or grades obtained by
                the student in the assignment or project done by us.
              </li>
              <li>
                Our responsibility as a service provider ends the moment the
                student is satisfied by the quality of the content drafted,
                written and delivered, and agrees to close the assignment order
              </li>
              <li>
                The order for an assignment or project is confirmed and placed
                only once the user sends us either full payment in advance or
                50% of the total order value.
              </li>
              <li>
                Your complete assignment will be sent to you only upon receiving
                the remaining amount. For more details visit the payment policy
              </li>
              <li>
                Upon receiving the assignment, if you feel there are some edits
                to be made you can get it done.
              </li>
              <li>
                {' '}
                You get two times complimentary changes. For details on
                modifications and changes to be made in the assignment, please
                visit the change policy
              </li>
              <li>
                If you opt for the hard copy of handwritten and copy-paste
                assignments, please make sure you let us know the shipping
                address within 2 days of completion of the assignment. Post
                that, Bluepen Assignment Private Limited will not be responsible for the ownership and
                shipping of the assignments
              </li>
              <li>
                For technical projects like mini-projects, final year projects,
                hardware, software, or any coding assignment and projects, we
                take full responsibility for running it in your system and
                ensuring that it is fully functional, but only once.
              </li>
              <li>
                Once the project is closed, if any problem arises in the code or
                any functioning of the project, we won’t be responsible for the
                same.
              </li>
            </ul>
          </span>
          <span className="text-xl text-left font-bold">USER ELIGIBILITY</span>
          <span className="px-5  py-8 text-md md:text-xl text-gray-800 max-w-5xl ">
            Use of the Website is available only to persons who can form legally
            binding contracts under Indian Contract Act, 1872. Persons who are
            “incompetent to contract” within the meaning of the Indian Contract
            Act, 1872 including minors, un-discharged insolvents etc. are not
            eligible to use the Website. If you are a minor i.e. under the age
            of 18 years, you shall not register as a User of the Website and
            shall not use the website. As a minor if you wish to use the
            website, such use may be made by your legal guardian or parents on
            the Website. Blue Pen reserves the right to terminate your
            membership and / or refuse to provide you with access to the
            Website.
          </span>
          <span className="text-xl text-left font-bold">
            YOUR ACCOUNT AND REGISTRATION OBLIGATIONS
          </span>
          <span className="px-5  py-8 text-md md:text-xl text-gray-800 max-w-5xl ">
            If You use the Website, You shall be responsible for maintaining the
            confidentiality of your Display Name and Password and You shall be
            responsible for all activities that occur under your Display Name
            and Password. You agree that if You provide any information that is
            untrue, inaccurate, not current or incomplete or We have reasonable
            grounds to suspect that such information is untrue, inaccurate, not
            current or incomplete, or not in accordance with the this Terms of
            Use, We shall have the right to indefinitely suspend or terminate or
            block access of your membership on the Website and refuse to provide
            You with access to the Website.
          </span>
          <span className="text-xl text-left font-bold">COMMUNICATIONS</span>
          <span className="px-5  py-8 text-md md:text-xl text-gray-800 max-w-5xl ">
            When You use the Website or send emails or other data, information
            or communication to us, You agree and understand that You are
            communicating with Us through electronic records and You consent to
            receive communications via electronic records from Us periodically
            and as and when required. We may communicate with you by email or by
            such other mode of communication, electronic or otherwise.
          </span>
          <span className="text-xl text-left font-bold">CHARGES</span>
          <span className="px-5  py-8 text-md md:text-xl text-gray-800 max-w-5xl ">
            Membership on the Website is free. Blue Pen does not charge any fee
            for browsing the Website. Blue Pen Limited reserves the right to
            change its Fee Policy from time to time. In particular, Blue Pen may
            at its sole discretion introduce new services and modify some or all
            of the existing services offered on the Website. In such an event
            Blue Pen reserves the right to introduce fees for the new services
            offered or amend/introduce fees for existing services, as the case
            may be. Changes to the fee policy shall be posted on the Website and
            such changes shall automatically become effective immediately after
            they are posted on the Website. Unless otherwise stated, all fees
            shall be quoted in Indian Rupees. You shall be solely responsible
            for compliance of all applicable laws including those in India for
            making payments to Blue Pen Limited.
            <br /> <br />
            Once you place an order we reserve the right to deduct the mentioned
            cost of the ordered assignment. Any false transactions or stolen
            cards will immediately be reported to the law authorities. We will
            not be held liable for the consequences of an illegal transaction.
            In case the order is delayed, a full or partial refund will be paid
            to the client after complete evaluation of the situation from all
            aspects. However this facility doesn’t apply if the delay is due to
            factors from the client’s side. All documents will be delivered via
            email so accurate and up to the date information must be provided.
          </span>
          <span className="text-xl text-left font-bold">
            FREE ASSIGNMENT REVISION POLICY
          </span>
          <span className="px-5  py-8 text-md md:text-xl text-gray-800 max-w-5xl ">
            If a client isn’t pleased with the received document he/she can
            avail the startling offer of free revisions. This actually befalls
            seldom however even when it does the client becomes gratified after
            only one or maximum two revisions. The free revision policy remains
            effective for a spell of 10-15 business days reliant on the length
            of the document. A trifling fee is vital for every revision later.
          </span>
          <span className="text-xl text-left font-bold">
            REFUND/ CANCELLATION STRATEGY
          </span>
          <span className="px-5  py-8 text-md md:text-xl text-gray-800 max-w-5xl ">
            Cancellation should be done before the transaction processing
            starts. Once the order is assigned to the writer and advance payment
            is made the order cannot be cancelled then. Also the charges of
            transaction placement are non refundable. The company reserves the
            authority of refund and cancellation appeal approval or denial.
          </span>
          <span className="text-xl text-left font-bold">
            TRANSACTION VERIFICATION PERIOD
          </span>
          <span className="px-5  py-8 text-md md:text-xl text-gray-800 max-w-5xl ">
            We have set a verification period for the clients to submit their
            billing information for the order to start getting processed. This
            time frame is reliant on the type and length of the document.
            <br />
            <br />
            Verification period of 8 hours for a 2-20 days delivery <br />
            <br />
            Verification period of 2 hours for a 12-24 hours delivery
            <br />
            <br />
            Verification period of 30 minutes for a 12 hours delivery
          </span>
          <span className="text-xl text-left font-bold">
            TRANSACTION DEFERRALS
          </span>
          <span className="px-5  py-8 text-md md:text-xl text-gray-800 max-w-5xl ">
            An order delivery is deferred due to the below mentioned reasons:
            Delayed payments: If the billing information is not verified on time
            Incorrect information: If the client wishes to make amendments in
            the document. If the client shows carelessness in checking the
            messages from the writer on time then those charges will not be
            repaid.
          </span>
          <span className="text-xl text-left font-bold">LICENSE</span>
          <span className="px-5  py-8 text-md md:text-xl text-gray-800 max-w-5xl ">
            Unless otherwise stated, Bluepen and/or its licensors own the
            intellectual property rights for all material on www.bluepen.co.in.
            All intellectual property rights are reserved. You may access this
            from www.bluepen.co.in for your own personal use subjected to
            restrictions set in these terms and conditions. You must not:
            <br />
            <br />
            <ul className="list-disc list-inside">
              <li>Republish material from www.bluepen.co.in</li>
              <li>Sell, rent or sub-license material from www.bluepen.co.in</li>
              <li>
                Reproduce, duplicate or copy material from www.bluepen.co.in
              </li>
              <li>Redistribute content from www.bluepen.co.in</li>
            </ul>
          </span>
        </div>
      </section>
    </div>
  );
}
